# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='icon_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Color'),
        ),
        migrations.AlterField(
            model_name='property',
            name='icon_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Icon'),
        ),
    ]
