# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160726_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Property'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
